# Установка nginx вынесена в отдельный файл, чтобы его можно было использовать в других ролях
- name: Установка nginx
  ansible.builtin.apt:
    name: nginx # устанавливаем nginx
    update_cache: true # обновляем список пакетов перед установкой
    state: present # устанавливаем пакет

- name: Создание страницы index для backend
  ansible.builtin.template:
    src: index.html.j2 # шаблон страницы index
    dest: /var/www/html/index.html # путь к странице index  
    mode: "0644" # режим доступа к файлу страницы

- name: Установка nginx в автозапуск и запуск сервиса
  ansible.builtin.service:
    name: nginx # имя сервиса
    state: started # запускаем сервис
    enabled: true # включаем автозапуск
