# inventory файл для Ansible. Описывает набор машин и их параметры.
# В данном случае указываются IP-адреса и пользователи для подключения по SSH.
linux:
  # общие параметры для всех машин
  vars:
    ansible_user: ubuntu # пользователь для подключения по SSH
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519 # путь к private ключу для подключения по SSH для машин в группе linux
  children:
    proxy: # группа машин с ролью proxy
      hosts: # список машин в группе proxy
        nginx-proxy-1: # имя машины
          ansible_host: 93.77.178.19 # IP-адрес машины
    backend: # группа машин с ролью backend
      hosts: # список машин в группе backend
        nginx-backend-1: # имя машины
          ansible_host: 158.160.53.223 # IP-адрес машины
        nginx-backend-2: # имя машины
          ansible_host: 158.160.33.78 # IP-адрес машины
