# Список пакетов для установки на ВМ
common_packages:
  - net-tools # просмотр сетевых параметров
  - dnsutils # просмотр DNS-серверов
  - wget # загрузка файлов
  - curl # отправка HTTP-запросов
  - mc # просмотр файлов
  - rsync # синхронизация файлов
